### ISSUE TITLE
pls give the example how use it,tks.

### ISSUE THREAD

**Issue by zwgmy** [Brokly/bl0942#2]
pls give the example how use it,tks.
Can this read the chip energy value directly?

**Comment by Brokly** [comment]
```yaml
uart:
  - id: uart_bus1
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 4800
    stop_bits: 1
    data_bits: 8
  - id: uart_bus2
    #tx_pin: GPIO5
    rx_pin: GPIO18
    baud_rate: 4800
    stop_bits: 1
    data_bits: 8
  - id: uart_bus3
    #tx_pin: GPIO5
    rx_pin: RX
    baud_rate: 4800
    stop_bits: 1
    data_bits: 8

sensor:
  - platform: bl0942
    update_interval: 5s
    uart_id: uart_bus1
    id: channel_1
    voltage:
      name: ${upper_devicename} Voltage1
    current:
      name: ${upper_devicename} Current1
    power:
      name: ${upper_devicename} Power1
    energy:
      name: ${upper_devicename} Energy1
    frequency:
      name: ${upper_devicename} Power Frequency1
  - platform: bl0942
    update_interval: 5s
    uart_id: uart_bus2
    id: channel_2
    voltage:
      name: ${upper_devicename} Voltage2
    current:
      name: ${upper_devicename} Current2
    power:
      name: ${upper_devicename} Power2
    energy:
      name: ${upper_devicename} Energy2
    frequency:
      name: ${upper_devicename} Power Frequency2
  - platform: bl0942
    update_interval: 5s
    uart_id: uart_bus3
    id: channel_3
    voltage:
      name: ${upper_devicename} Voltage3
    current:
      name: ${upper_devicename} Current3
    power:
      name: ${upper_devicename} Power3
    energy:
      name: ${upper_devicename} Energy3
    frequency:
      name: ${upper_devicename} Power Frequency3
```
